Repository desenvolvendo-me/ticket-event, pull requests merged in 2023-10, with the labels that each got.

#86 Feature/85 sorteio sera somente para os estudantes que tirarem nota no questionário acima de 70
  app/admin/events.rb
  app/admin/prize_draws.rb
  app/businesses/prize_draws/generator.rb
  app/models/prize_draw.rb
  app/models/ticket.rb
  config/locales/admin/event.pt-BR.yml
  config/locales/models/prize_draws.pt-BR.yml
  db/migrate/20230920133138_create_raffles.rb
  db/migrate/20230921121618_rename_raffle_to_prize_draws.rb
  db/migrate/20230921170542_change_prize_draw_table.rb
  db/seeds.rb
  spec/businesses/lessons/validator_spec.rb
  spec/businesses/prize_draws/generator_spec.rb
Labels: feature

#122 Request/121 checagem de disponibilidade de aula e evento
  Gemfile.lock
  app/businesses/access.rb
  app/businesses/access/checker.rb
  app/controllers/external/events_controller.rb
  app/controllers/external/lessons_controller.rb
  app/views/external/events/index.html.erb
  app/views/external/lessons/index.html.erb
  config/locales/businesses/access/checker.pt-BR.yml
  spec/businesses/access/checker_spec.rb
  spec/models/student_spec.rb
Labels: request

#120 Feature/101 permitir que infoprodutor importe um csv com os estudante para cadadastrar
  app/businesses/students/batch_creator.rb
  app/businesses/students/creator.rb
  app/businesses/tickets/builders.rb
  app/controllers/manager/students_controller.rb
  app/views/manager/students/index.html.erb
  app/views/manager/students/select_student_csv.html.erb
  config/locales/views/manager/student.pt-BR.yml
  config/routes.rb
  db/seeds.rb
  spec/businesses/students/bach_creator_spec.rb
  spec/businesses/students/creator_spec.rb
  spec/requests/manager/students_spec.rb
Labels: feature, internal
